version: '3'
services:
  user-db:
    image: mysql:8
    hostname: mrc-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - "/usr/local/docker/mysql/conf:/etc/mysql"
      - "/usr/local/docker/mysql/logs:/var/log/mysql"
      - "/usr/local/docker/mysql/data:/var/lib/mysql"
  # cart-db:
  #   image: mongo:4
  #   hostname: cart-db
  #   environment:
  #     MONGO_INITDB_ROOT_PASSWORD: dangerous
  # zookeeper:
  #   image: docker.io/bitnami/zookeeper:3.7
  #   ports:
  #     - "2181:2181"
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes
  # kafka:
  #   image: docker.io/bitnami/kafka:2
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #   depends_on:
  #     - zookeeper
